development:
  dialect: "mysql"
  database: {{envOr "DATABASE_DB_DEV" "sample_app_dev"}}
  host: {{envOr "DATABASE_HOST_DEV" "localhost"}}
  port: {{envOr "DATABASE_PORT_DEV" "3306"}}
  user: {{envOr "DATABASE_USER_DEV" "root"}}
  password: {{envOr "DATABASE_PASSWORD_DEV" "root"}}

test:
  dialect: "mysql"
  #
  # You can use a single URL string for the same configuration:
  #
  #url: "mysql://root:root@(localhost:3306)/sample_app_test?parseTime=true&multiStatements=true&readTimeout=3s"
  #
  # Note that if you use `url`, other configurations are silently ignored.
  # In this case, the URL must contain all required connection parameters.
  #
  database: {{envOr "DATABASE_DB_TEST" "sample_app_test"}}
  host: {{envOr "DATABASE_HOST_TEST" "localhost"}}
  port: {{envOr "DATABASE_PORT_TEST" "3306"}}
  user: {{envOr "DATABASE_USER_TEST" "root"}}
  password: {{envOr "DATABASE_PASSWORD_TEST" "root"}}

production:
  #
  # You can also use environmental variables to override values in this config.
  #
  #url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/sample_app_production?parseTime=true&multiStatements=true&readTimeout=3s"}}
  #
  dialect: "mysql"
  database: {{envOr "DATABASE_DB" "sample_app_production"}}
  host: {{envOr "DATABASE_HOST" "localhost"}}
  port: {{envOr "DATABASE_PORT" "3306"}}
  user: {{envOr "DATABASE_USER" "root"}}
  password: {{envOr "DATABASE_PASSWORD" "root"}}
  #
  # And you can also override connection parameters by setting it under options.
  #
  #options:
  #  parseTime: true
  #  multiStatements: true
  #  readTimeout: 3s
  #  encoding: "utf8mb4_general_ci"
  #
  # CAUTION!
  #   `parseTime` and` multiStatements` must be set to `true` to work properly.
  #   If you are not sure, do not change (or set) these values.
